package proxy

import "github.com/prometheus/client_golang/prometheus"

// RequestIDMetrics holds Prometheus counters for request ID middleware.
type RequestIDMetrics struct {
	generated  prometheus.Counter
	propagated prometheus.Counter
}

// NewRequestIDMetrics registers and returns RequestIDMetrics.
// Falls back to prometheus.DefaultRegisterer when reg is nil.
func NewRequestIDMetrics(reg prometheus.Registerer) *RequestIDMetrics {
	if reg == nil {
		reg = prometheus.DefaultRegisterer
	}
	m := &RequestIDMetrics{
		generated: prometheus.NewCounter(prometheus.CounterOpts{
			Name: "prom_label_enforcer_request_id_generated_total",
			Help: "Total number of request IDs generated by the middleware.",
		}),
		propagated: prometheus.NewCounter(prometheus.CounterOpts{
			Name: "prom_label_enforcer_request_id_propagated_total",
			Help: "Total number of request IDs propagated from incoming headers.",
		}),
	}
	reg.MustRegister(m.generated, m.propagated)
	return m
}

// RecordGenerated increments the generated counter.
func (m *RequestIDMetrics) RecordGenerated() {
	if m == nil {
		return
	}
	m.generated.Inc()
}

// RecordPropagated increments the propagated counter.
func (m *RequestIDMetrics) RecordPropagated() {
	if m == nil {
		return
	}
	m.propagated.Inc()
}
